version: '3.8'

services:
  fast-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-inventory
      - postgres-product
      - kafka
      - mongodb

  postgres-product:
    restart: always
    ports:
      - "5432:5432"
    image: postgres:alpine
    environment:
      - USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products

  postgres-inventory:
    restart: always
    ports:
      - "5433:5433"
    image: postgres:alpine
    environment:
      - USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    command:
      - "postgres"
      - "-c"
      - "port=5433"

  mongodb:
    ports:
      - "27017:27017"
    image: mongo

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CREATE_TOPICS=order_topic
    depends_on:
      - zookeeper